### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by Lawerencium** [coolmann24/TerrainFinderCpp#1]
Hello coolmann24,

Are you still working on making an interface? I'm not such a code-hero myself so can't get it to work atm.
I'm trying to use this on anarchy, so I've used the multithreaded version for some time now, but that takes about 130 hours of calculation to get a coordinate right in a 20mil*20mil box, which is a reasonable size, but not such a nice time period xD

I'm really looking for ward to this project. please hmu if you've finished this 

greetings

**Comment by coolmann24** [comment]
yeah im still planning to make a gui for this and actually finished most of it a while back but got busy with other stuff. will eventually finish it at some point but got held up with getting the library to work with qt creator. if you know someone that knows how to set up and compile a C++ program you can use this already by running threadedSearch in Search.h

**Comment by coolmann24** [comment]
finished the gui app: https://www.youtube.com/watch?v=Trocrqd038o
